### ISSUE TITLE
Added Topic Presentation PowerPoint

### ISSUE THREAD

**Issue by codesoftly** [EhrgoHealth/CS6440#11]
Please review/modify/add information to the PowerPoint added in the master branch. This is what we will be submitting (with Donna's voice over) as our submission for the first milestone grade.

Note, I couldn't really find any good gantt chart tools. I downloaded Office Timeline Free from https://www.officetimeline.com/download and installed it as an Add-In to PowerPoint.  Please look at how I broke down the project - I can go far more granular if need be - but we can run into trouble with that level of detail.

**Comment by tparnell8** [comment]
Honestly, I quite like it... :+1:

**Comment by Kakarot** [comment]
Everything looks well polished. As a new member, my perspective may be similar to the grader who is reading about the project for the first time. The only questions I have might be about how the patient is inserting data into "home" access. I'm not exactly clear with the implementation of the architecture yet or the relationship between the data we reading versus storing.

* **Read**: We are creating a plugin to read treatment analysis data from EHS (this will be the FHIR requirement, correct?). 
* **Store**: The user being able to enter data such as "food" would be our own local database server-side, correct?

To be fair, the deliverable requirements do not mention anything about architecture, I was just offering a perspective since the question came to mind as I read it.

I believe all the requirements are met:

Presentation Criteria:
• Introduce us to your project and tell us about your project topic. One person can
present a whole video, but a different person should present each time. (Each
team member should present in at least one video) **Satisfied**
• Presentation Quality (timeliness, clarity, interest, poise, enthusiasm, visual
interest) **Satisfied**
• Research (market context, needs, survey, interviews, etc) **Satisfied (Interview)**
• Business Case (what problem, for whom, benefits to end users, solutions, etc)
• Gantt Chart of your project plan identifying resource allocations **Satisfied**
• Must be narrated. **Pending (Donna will narrate, I believe it was mentioned)**

**Comment by dbcarey** [comment]
The PowerPoint looks really good.  I'll add some narration before tomorrow's meeting time.

**Comment by codesoftly** [comment]
James - I added the **store** component for "food" and "allergies" - I planned to talk about it tomorrow before Donna's narration. I can't see this system working without the "home" component.  Ideally we would enable this to leverage other health benefit tools such as calorie counting and goal setting (not this semester, but beyond).

You are obviously correct as far as your other assumptions as well. We can add some technical details - _and in fact should in the narration_ - but I think that might be beyond the scope of this initial submission (i.e. I can't describe an adequate architecture for this in 5 minutes, much less the problem statement, research, business case, etc.).

- Eric

**Comment by dbcarey** [comment]
Then I will wait until after the meeting to start the narration part.
